
stages:
- stage: Tests
  jobs:
  - job: Test
    strategy:
      matrix:
        # python 3.7
        linuxPY37:
          imageName: 'ubuntu-latest'
          python.version: '3.7'
          tox.env: py37
        macPY37:
          imageName: 'macOS-latest'
          python.version: '3.7'
          tox.env: py37
        windowsPY37:
          imageName: 'windows-latest'
          python.version: '3.7'
          tox.env: py37

        # python 3.8
        linuxPY38:
          imageName: 'ubuntu-latest'
          python.version: '3.8'
          tox.env: py38
        macPY38:
          imageName: 'macOS-latest'
          python.version: '3.8'
          tox.env: py38
        windowsPY38:
          imageName: 'windows-latest'
          python.version: '3.8'
          tox.env: py38

        # python 3.9
        linuxPY39:
          imageName: 'ubuntu-latest'
          python.version: '3.9'
          tox.env: py39
        macPY39:
          imageName: 'macOS-latest'
          python.version: '3.9'
          tox.env: py39
        windowsPY39:
          imageName: 'windows-latest'
          python.version: '3.9'
          tox.env: py39

        # manifest
        manifestTest:
          python.version: '3.9'
          tox.env: manifest
          imageName: 'ubuntu-latest'
    pool:
      vmImage: $(imageName)
    steps:
    - template: python-steps.yml
      parameters:
        toxEnv: $(tox.env)
