
stages:
- stage: Tests
  jobs:
  - job: Test
    strategy:
      matrix:
        # python 3.7
        linuxTestPY37:
          imageName: 'ubuntu-latest'
          python.version: '3.7'
          tox.env: py37
        macTestPY37:
          imageName: 'macOS-latest'
          python.version: '3.7'
          tox.env: py37
        windowsTestPY37:
          imageName: 'windows-latest'
          python.version: '3.7'
          tox.env: py37

        # python 3.8
        linuxTestPY38:
          imageName: 'ubuntu-latest'
          python.version: '3.8'
          tox.env: py38
        macTestPY38:
          imageName: 'macOS-latest'
          python.version: '3.8'
          tox.env: py38
        windowsTestPY38:
          imageName: 'windows-latest'
          python.version: '3.8'
          tox.env: py38

        # python 3.9
        linuxTestPY39:
          imageName: 'ubuntu-latest'
          python.version: '3.9'
          tox.env: py39
        macTestPY39:
          imageName: 'macOS-latest'
          python.version: '3.9'
          tox.env: py39
        windowsTestPY39:
          imageName: 'windows-latest'
          python.version: '3.9'
          tox.env: py39

        # manifest
        manifestTest:
          python.version: '3.9'
          tox.env: manifest
          imageName: 'ubuntu-latest'
    pool:
      vmImage: $(imageName)
    steps:
    - template: python-steps.yml
      parameters:
        toxEnv: $(tox.env)
