
stages:
- stage: Packages
  jobs:
  - job: Packaging
    strategy:
      matrix:
        # packaging
        linuxPackaging:
          imageName: 'ubuntu-latest'
          python.version: '3.9'
          tox.env: packaging
        macPackaging:
          imageName: 'macOS-latest'
          python.version: '3.9'
          tox.env: packaging
        windowsPackaging:
          imageName: 'windows-latest'
          python.version: '3.9'
          tox.env: packaging
    pool:
      vmImage: $(imageName)
    steps:
    # PyPi
    - task: TwineAuthenticate@1
      condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/v')
      inputs:
        pythonUploadServiceConnection: PyPIConnection

    - script: python -m pip install --upgrade --quiet setuptools wheel twine

    - script: python setup.py sdist bdist_wheel

    - script: python -m twine check "dist/*whl" "dist/*tar.gz"

    - script: python -m twine upload -r PyPIConnection --config-file $(PYPIRC_PATH) "dist/*whl" "dist/*tar.gz"
      condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/v')

    # Standalone app
    - template: python-steps.yml
      parameters:
        toxEnv: $(tox.env) -- -o dist/image-to-scan

    - publish: $(System.DefaultWorkingDirectory)/dist/image-to-scan
      condition: and(
                  succeeded(),
                  eq(variables['Build.SourceBranch'], 'refs/heads/master')
                 )
      artifact: image-to-scan-$(imageName)

    - task: GithubRelease@0
      displayName: 'Create GitHub Release'
      condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/v')
      inputs:
        gitHubConnection: image-to-scan
        assets: $(System.DefaultWorkingDirectory)/dist/image-to-scan
